### ISSUE TITLE
executeActionsEmail fails

### ISSUE THREAD

**Issue by clkao** [keycloak/keycloak-admin-client#72]
client.users.executeActionsEmail fails with:
`Error { errorMessage: 'undefined not enabled' }`

It seems the the REST query should have `lifespan=43200` in its parameter.

**Comment by hepuxuan** [comment]
We are facing the same issue, however I don't believe the issue is with lifespan query since it's optional according to api doc(https://www.keycloak.org/docs-api/3.2/rest-api/index.html#_parameters_231) but we need a null check before adding redirectUri query.
I've create another pull request to fix this issue: https://github.com/keycloak/keycloak-admin-client/pull/89/files

**Comment by stianst** [comment]
This library is no longer being maintained, please use https://github.com/keycloak/keycloak-nodejs-admin-client instead
